### PR TITLE
Added BME680 support

### PR DESCRIPTION
**Pull request by miccgn**
Added support libraries for Adafruit BME680. Included Gas values (in kOhm) to sensor readings.
Tried to extend the index.js file for WebInterface, however, seems the other .js files need some work as well.

### CODE REVIEW

**Comment by o0shojo0o** [comment]
Thank you for your contribution to this project, I will probably get to see your pull this weekend and complete the web ui integration.

**Comment by hamster65** [comment]
How can the gas value be translated to something meaningful? I think it drifts over time and also depends on humidity or/and temperature?

**Comment by o0shojo0o** [comment]
I can not answer this, do not know myself with it.

**Comment by miccgn** [comment]
Hi,
I don't know either :) I have to admit: I bought the BME680 because it was available, while the BME280 wasn't.
My first experiments this week showed that in the first 20mins after booting, the value raised, then becomes stagnant. When I exhale into the sensor, it drops significantly. When I open a window, it drops significantly. So, for home purposes, it **might** become an indicator of how well aired the room is.

But, nevertheless: even if it turns out to be meaningless, I still want to read temp/humidity from the sensor, so supporting it in the software would be great.

**Pull request merged**
