### PR TITLE
Rearrange and fix WebUI

### PR DESCRIPTION
**Pull request by miccgn**
Rearranged some of the settings on Options & Sensor pages.

On the dashboard, Button Data is not provided in the corresponding section. Might be a typo which I corrected. @o0shojo0o Please check if this area gets messages now (I integrated a first message to be sent on ws connect).

### CODE REVIEW

**Comment by miccgn** [comment]
Buttons for MP3 control added

**Comment by o0shojo0o** [comment]
I will only get to it the days, sorry

**Comment by miccgn** [comment]
> I will only get to it the days, sorry

No hurry! I really need to spend a few evenings on other topics as well ;)

**Comment by o0shojo0o** [comment]
Thanks! ;)

**Pull request merged**
