### PR TITLE
Add ZigZagWipe, bitmapWipe and randomization for wipes

### PR DESCRIPTION
**Pull request by miccgn**
Create new switchAnimation effect "zigzagWipe". Takes color as optional parameter.

Create new switchAnimation effect "bitmapWip". Allows to have a bitmap eat the old display.
The bitmap must not be animated, it must have height=8. Width can be anything between 1 and 32.
New parameters to switchAnimation:
"animation": "bitmapWipe",
"data": [your bitmap],
"w":8 //or any other width of your bitmap

### CODE REVIEW

**Comment by o0shojo0o** [comment]
What still has to be adjusted here? https://docs.bastelbunker.de/pixelit/api.html#switch-animation
Are the values then always necessary? 
Because then I also have to reprogram the Node-Red.

**Comment by miccgn** [comment]
Just mention the new animations.
{
    "switchAnimation": {
        "aktiv": true, // [ true | false ]
        "animation": "fade" // [ "fade" | "coloredBarWipe" | "zigzagWipe" | "bitmapWipe" ] [,]
        // [Optional for zigzagWipe, ignored for other animations]
        "color": {
            "r": 255, // [0 - 255]
            "g": 255, // [0 - 255]
            "b": 255 // [0 - 255]
        },
        // [alternative to color]
        "hexColor": "#FFFFFF",
        // [required for bitmapWipe, ignored for other animations]
        "data": [
                    [0, 0, 0, 0, 0, 0],
                    [0, 0, 0, 0, 0, 0],
                    [0, 0, 0, 0, 0, 0]
                ],
         // [required for bitmapWipe, ignored for other animations]
         "width": 8  //may be 1...32, height always needs to be 8
     }
}

**Comment by miccgn** [comment]
There are no breaking changes for previous behaviour!

**Comment by o0shojo0o** [comment]
Thanks for this, I really like your work!

**Pull request merged**
